using HydroEspinaca.Shared.Abstractions;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WeatherService.Domain.Persistence.Documents;

/// <summary>
/// MongoDB document representing a weather alert generated by the system.
/// </summary>
public class WeatherAlertDocument : IIdentifiableMutable
{
    [BsonId]
    [BsonRepresentation(BsonType.ObjectId)]
    public string Id { get; set; } = string.Empty;

    [BsonElement("fuzzy_system_id")]
    public string FuzzySystemId { get; set; } = string.Empty;

    [BsonElement("alert_type")]
    public string AlertType { get; set; } = string.Empty;

    [BsonElement("severity")]
    public string Severity { get; set; } = "warning";

    [BsonElement("title")]
    public string Title { get; set; } = string.Empty;

    [BsonElement("message")]
    public string Message { get; set; } = string.Empty;

    [BsonElement("recommendation")]
    public string Recommendation { get; set; } = string.Empty;

    [BsonElement("forecast_datetime")]
    public DateTime ForecastDatetime { get; set; }

    [BsonElement("forecast_value")]
    [BsonIgnoreIfNull]
    public double? ForecastValue { get; set; }

    [BsonElement("forecast_condition")]
    [BsonIgnoreIfNull]
    public string? ForecastCondition { get; set; }

    [BsonElement("government_alert")]
    public bool GovernmentAlert { get; set; }

    [BsonElement("notified_users")]
    public List<NotifiedUserDocument> NotifiedUsers { get; set; } = [];

    [BsonElement("created_at")]
    public DateTime CreatedAt { get; set; }

    public void SetId(string id) => Id = id;
}

/// <summary>
/// MongoDB sub-document representing a user who was notified about a weather alert.
/// </summary>
public class NotifiedUserDocument
{
    [BsonElement("user_id")]
    public string UserId { get; set; } = string.Empty;

    [BsonElement("channels")]
    public List<string> Channels { get; set; } = [];

    [BsonElement("sent_at")]
    public DateTime SentAt { get; set; }

    [BsonElement("is_read")]
    public bool IsRead { get; set; }
}
