from .CreateFuzzyTermHandler import CreateFuzzyTermHandler
from .UpdateFuzzyTermHandler import UpdateFuzzyTermHandler
from .DeleteFuzzyTermHandler import DeleteFuzzyTermHandler
from .GetAllFuzzyTermsHandler import GetAllFuzzyTermsHandler
from .GetFuzzyTermByIdHandler import GetFuzzyTermByIdHandler
