#ifndef SECRETS_H
#define SECRETS_H

// WiFi Credentials
#define WIFI_SSID "REPLACE_WITH_YOUR_WIFI_SSID"
#define WIFI_PASSWORD "REPLACE_WITH_YOUR_WIFI_PASSWORD"

// MQTT Credentials
#define MQTT_SERVER "REPLACE_WITH_MQTT_BROKER_IP"
#define MQTT_PORT 1883
#define MQTT_USER "REPLACE_WITH_MQTT_USER"
#define MQTT_PASSWORD "REPLACE_WITH_MQTT_PASSWORD"
#define MQTT_CLIENT_ID "esp32-001"

#endif
