<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HydroEspinaca.Shared" Version="1.0.3-dev-20260425071801" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChatbotService.Application\ChatbotService.Application.csproj" />
    <ProjectReference Include="..\ChatbotService.Infrastructure\ChatbotService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
