using WeatherService.Domain.Entities;

namespace WeatherService.Domain.Interfaces;

/// <summary>
/// Repository interface for managing WeatherAlert entities.
/// This repository abstracts the data access layer for storing and retrieving
/// weather alerts generated by the system, allowing for querying by various filters,
/// </summary>
public interface IWeatherAlertRepository
{
    /// <summary>
    /// Creates a new weather alert entry in the repository. 
    /// The alert should contain all necessary information,
    /// including the fuzzy system ID, alert type, description, 
    /// timestamp, and any relevant metadata.
    /// </summary>
    /// <param name="alert">The weather alert entity to create.</param>
    /// <param name="ct">Cancellation token for the operation.</param>
    /// <returns>The created weather alert with its assigned ID.</returns>
    Task<WeatherAlert> CreateAsync(WeatherAlert alert, CancellationToken ct = default);
    
    /// <summary>
    /// Retrieves weather alerts based on optional filters such as fuzzy system ID,
    /// user ID, date range, and read/unread status.
    /// </summary>
    /// <param name="fuzzySystemId">Filter by fuzzy system ID (optional).</param>
    /// <param name="userId">Filter by user ID (optional, to get alerts relevant to a specific user).</param>
    /// <param name="from">Filter alerts from this date/time (optional).</param>
    /// <param name="to">Filter alerts up to this date/time (optional).</param>
    /// <param name="unreadOnly">If true, only return unread alerts (optional).</param>
    /// <param name="ct">Cancellation token for the operation.</param>
    /// <returns>List of weather alerts matching the specified filters.</returns
    Task<List<WeatherAlert>> GetByFiltersAsync(
        string? fuzzySystemId = null,
        string? userId = null,
        DateTime? from = null,
        DateTime? to = null,
        bool? unreadOnly = null,
        CancellationToken ct = default);

    /// <summary>
    /// Marks a specific alert as read for a given user. 
    /// This method updates the alert's status
    /// </summary>
    /// <param name="alertId">The ID of the alert to mark as read.</param>
    /// <param name="userId">The ID of the user for whom the alert should be marked as read.</param>
    /// <param name="ct">Cancellation token for the operation.</param>
    /// <returns>True if the operation was successful, false if the alert or user was not found.</returns>
    Task<bool> MarkAsReadAsync(string alertId, string userId, CancellationToken ct = default);
    
    /// <summary>
    /// Checks if a similar alert (same type and fuzzy system ID) has been sent within the deduplication window.
    /// </summary>
    /// <param name="alertType">The type of the alert (e.g., "heavy_rain", "high_wind").</param>
    /// <param name="fuzzySystemId">The fuzzy system ID associated with the alert.</param>
    /// <param name="deduplicationHours">The number of hours for the deduplication window.</param>
    /// <param name="ct">Cancellation token for the operation.</param>
    /// <returns>True if a similar alert exists within the deduplication window, otherwise false.</returns>
    Task<bool> ExistsRecentAsync(string alertType, string fuzzySystemId, int deduplicationHours, CancellationToken ct = default);
    
    /// <summary>
    /// Adds a notified user to the alert's record, 
    /// indicating that this user has been sent the alert.
    /// </summary>
    /// <param name="alertId">The ID of the alert.</param>
    /// <param name="notifiedUser">The notified user information to add.</param>
    /// <param name="ct">Cancellation token for the operation.</param>
    Task AddNotifiedUserAsync(string alertId, NotifiedUser notifiedUser, CancellationToken ct = default);
}
