<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BiService.Application\BiService.Application.csproj" />
    <ProjectReference Include="..\BiService.Domain\BiService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HydroEspinaca.Shared" Version="1.0.3-dev-20260425071801" />
    <PackageReference Include="MongoDB.Driver" Version="3.4.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
