from .GetAllFuzzyVariablesQuery import GetAllFuzzyVariablesQuery
from .GetFuzzyVariableByIdQuery import GetFuzzyVariableByIdQuery
from .GetFuzzyVariablesBySystemQuery import GetFuzzyVariablesBySystemQuery
