<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ChatbotService.Application\ChatbotService.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Google.GenAI" Version="1.1.0" />
    <PackageReference Include="HydroEspinaca.Shared" Version="1.0.3-dev-20260425071801" />
    <PackageReference Include="MongoDB.Driver" Version="3.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
